name: superset

x-superset-image: &superset-image tapo44ek/superset-custom:2026-05-15

x-superset-env: &superset-env
  env_file:
    - path: docker/.env
      required: true
    - path: docker/.env-local
      required: false

services:
  redis:
    image: redis:7
    container_name: superset_cache
    restart: unless-stopped
    volumes:
      - redis:/data

  db:
    image: postgres:17
    container_name: superset_db
    restart: unless-stopped
    env_file:
      - path: docker/.env
        required: true
      - path: docker/.env-local
        required: false
    volumes:
      - db_home:/var/lib/postgresql/data
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro

  superset-init:
    image: *superset-image
    container_name: superset_init
    command: ["/app/docker/docker-init.sh"]
    <<: *superset-env
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    user: "root"
    volumes:
      - superset_home:/app/superset_home
    restart: "no"
    healthcheck:
      disable: true

  superset:
    image: *superset-image
    container_name: superset_app
    command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
    <<: *superset-env
    user: "root"
    restart: unless-stopped
    ports:
      - "8088:8088"
    depends_on:
      superset-init:
        condition: service_completed_successfully
    volumes:
      - superset_home:/app/superset_home

  superset-worker:
    image: *superset-image
    container_name: superset_worker
    command: ["/app/docker/docker-bootstrap.sh", "worker"]
    <<: *superset-env
    restart: unless-stopped
    depends_on:
      superset-init:
        condition: service_completed_successfully
    user: "root"
    volumes:
      - superset_home:/app/superset_home
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "celery -A superset.tasks.celery_app:app inspect ping -d celery@$$HOSTNAME",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  superset-worker-beat:
    image: *superset-image
    container_name: superset_worker_beat
    command: ["/app/docker/docker-bootstrap.sh", "beat"]
    <<: *superset-env
    restart: unless-stopped
    depends_on:
      superset-init:
        condition: service_completed_successfully
    user: "root"
    volumes:
      - superset_home:/app/superset_home
    healthcheck:
      disable: true

volumes:
  superset_home:
  db_home:
  redis:
